# FSFHap port — stage 1a: segregating-site test (whichSitesSegregateCorrectly).
# Faithful-port unit checks: the binomial dominance test must keep backcross-freq
# sites in backcross mode, 1:1 sites in F2 mode, and drop monomorphic/error sites.
#
# Sites are generated by TARGET MINOR-ALLELE FREQUENCY — the only quantity the
# kernel keys on. There is deliberately no design/het knob here: the segregation
# kernel has no notion of a breeding design (that lives upstream), so the test
# stays design-agnostic.

# one site's g vector (0/1/2) with an exact minor(ALT)-allele frequency `maf`.
# n_alt alleles are placed as ALT-homs (+ one het if odd) so 2*nAltHom+nHet = n_alt.
mk_site <- function(n, maf) {
  n_alt <- round(2 * n * maf)
  g <- integer(n)
  n_hom <- n_alt %/% 2L
  if (n_hom > 0) g[seq_len(n_hom)] <- 2L
  if (n_alt %% 2L == 1L) g[n_hom + 1L] <- 1L
  as.integer(g)
}

make_G <- function(n = 120L) {
  G <- cbind(
    bc       = mk_site(n, 0.25),      # MAF 0.25 -> backcross model
    f2       = mk_site(n, 0.50),      # MAF 0.50 -> F2 model
    mono     = mk_site(n, 0.00),      # single allele -> drop
    nearmono = mk_site(n, 1 / (2 * n))# one minor allele (~error) -> drop
  )
  storage.mode(G) <- "integer"
  G
}

test_that("backcross mode keeps only the MAF-0.25 site", {
  G <- make_G()
  res <- fsfhap_segregating_sites_cpp(G, max_missing = 0.9, ratio = 0.25)
  expect_equal(res$seg, c(TRUE, FALSE, FALSE, FALSE))
})

test_that("F2 mode keeps only the MAF-0.50 site", {
  G <- make_G()
  res <- fsfhap_segregating_sites_cpp(G, max_missing = 0.9, ratio = 0.5)
  expect_equal(res$seg, c(FALSE, TRUE, FALSE, FALSE))
})

test_that("monomorphic sites are untested (NA model probs) and dropped", {
  G <- make_G()
  res <- fsfhap_segregating_sites_cpp(G, max_missing = 0.9, ratio = 0.25)
  expect_true(is.na(res$pmono[3]))       # 'mono' column: biallelic gate fails
  expect_false(res$seg[3])
  expect_equal(res$Mn[3], 0L)            # no minor allele
})

test_that("allele counts are diploid (2*hom + het)", {
  # 10 taxa: 6 REF-hom, 2 het, 2 ALT-hom -> ref=2*6+2=14, alt=2*2+2=6
  g <- as.integer(c(rep(0, 6), 1, 1, 2, 2))
  G <- matrix(g, ncol = 1L); storage.mode(G) <- "integer"
  res <- fsfhap_segregating_sites_cpp(G, max_missing = 0.9, ratio = 0.25)
  expect_equal(res$Mj[1], 14L)
  expect_equal(res$Mn[1], 6L)
})

test_that("a site over max_missing is dropped", {
  n <- 100L
  g <- mk_site(n, 0.25); g[1:60] <- 3L      # 60% missing
  G <- matrix(g, ncol = 1L); storage.mode(G) <- "integer"
  res <- fsfhap_segregating_sites_cpp(G, max_missing = 0.5, ratio = 0.25)
  expect_false(res$seg[1])
  expect_true(is.na(res$pquarter[1]))
  expect_equal(round(res$p_missing[1], 2), 0.60)
})

test_that(".fsfhap_segregating wrapper coerces storage mode", {
  G <- make_G(); storage.mode(G) <- "double"  # non-integer input
  res <- .fsfhap_segregating(G, ratio = 0.25)
  expect_equal(res$seg, c(TRUE, FALSE, FALSE, FALSE))
})

# ---- stage 1b: same-tag filter + BC parent-allele calling -------------------

major_is_ref_of <- function(G) {
  (2 * colSums(G == 0L) + colSums(G == 1L)) >= (2 * colSums(G == 2L) + colSums(G == 1L))
}

test_that("same-tag filter drops within-64bp high-R2 SNPs, keeps distant/low-R2", {
  n <- 40L
  s1 <- as.integer(c(rep(0L, 10), rep(2L, 30)))         # hom-only -> R2=1 with copies
  s4 <- as.integer(c(rep(2L, 20), rep(0L, 20)))         # balanced, orthogonal to s5
  s5 <- as.integer(ifelse(seq_len(n) %% 2L == 0L, 2L, 0L))
  G  <- cbind(s1, s1, s1, s4, s5); storage.mode(G) <- "integer"
  pos <- as.integer(c(100, 140, 150, 170, 200))         # s1-run <64bp; s4 at +70; s5 <64 of s4
  keep <- fsfhap_same_tag_keep_cpp(G, pos, major_is_ref_of(G), 0.8)
  # s1 anchor; s2,s3 same tag (R2=1) dropped; s4 distant -> anchor; s5 low-R2 -> kept
  expect_equal(keep, c(TRUE, FALSE, FALSE, TRUE, TRUE))
})

test_that("same-tag filter keeps everything when SNPs are >=64bp apart", {
  n <- 20L
  G <- cbind(as.integer(c(rep(0L, 5), rep(2L, 15))),
             as.integer(c(rep(2L, 15), rep(0L, 5)))); storage.mode(G) <- "integer"
  pos <- as.integer(c(1000, 2000))                       # 1000bp apart
  expect_equal(fsfhap_same_tag_keep_cpp(G, pos, major_is_ref_of(G), 0.8), c(TRUE, TRUE))
})

test_that("BC parent-calling recodes so the major allele is A-hom (0)", {
  n <- 40L
  # 3 segregating sites (MAF 0.25) where ALT is the MAJOR allele -> recode must flip
  site <- as.integer(c(rep(2L, 30), rep(0L, 10)))        # alt 60 / ref 20 -> MAF 0.25
  G <- cbind(site, site, site); storage.mode(G) <- "integer"
  pos <- as.integer(c(100, 200, 300))                    # >64bp apart: same-tag keeps all
  res <- .fsfhap_call_parents_bc(G, pos, max_missing = 1, min_gametes = 0L)
  expect_equal(res$n_kept_sites, 3L)
  # after recode, A(major)-hom coded 0 should dominate C(minor)-hom coded 2
  for (s in seq_len(ncol(res$G)))
    expect_gt(sum(res$G[, s] == 0L), sum(res$G[, s] == 2L))
  expect_false(any(res$major_is_ref))                    # ALT was major at every kept site
})

test_that("BC parent-calling drops low-coverage taxa", {
  n <- 40L
  site <- as.integer(c(rep(2L, 30), rep(0L, 10)))
  G <- cbind(site, site, site); storage.mode(G) <- "integer"
  G[1, ] <- 3L                                           # taxon 1: all missing on kept sites
  pos <- as.integer(c(100, 200, 300))
  res <- .fsfhap_call_parents_bc(G, pos, max_missing = 1, min_gametes = 0L)
  expect_false(1L %in% res$keep_taxa)                    # 0 gametes, not > 0 -> dropped
  expect_equal(length(res$keep_taxa), n - 1L)
})

test_that("BC parent-calling errors on pos/site length mismatch", {
  G <- make_G(); expect_error(.fsfhap_call_parents_bc(G, pos = 1:2), "length\\(pos\\)")
})
