// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// count_emission_loglik_cpp
NumericMatrix count_emission_loglik_cpp(IntegerVector n, IntegerVector a, NumericVector theta, double conc);
RcppExport SEXP _nilHMM_count_emission_loglik_cpp(SEXP nSEXP, SEXP aSEXP, SEXP thetaSEXP, SEXP concSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type n(nSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type conc(concSEXP);
    rcpp_result_gen = Rcpp::wrap(count_emission_loglik_cpp(n, a, theta, conc));
    return rcpp_result_gen;
END_RCPP
}
// forward_backward_cpp
NumericMatrix forward_backward_cpp(NumericVector log_init, NumericMatrix log_trans, NumericMatrix log_emit);
RcppExport SEXP _nilHMM_forward_backward_cpp(SEXP log_initSEXP, SEXP log_transSEXP, SEXP log_emitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type log_init(log_initSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type log_trans(log_transSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type log_emit(log_emitSEXP);
    rcpp_result_gen = Rcpp::wrap(forward_backward_cpp(log_init, log_trans, log_emit));
    return rcpp_result_gen;
END_RCPP
}
// rtiger_getlogpsi_cpp
NumericMatrix rtiger_getlogpsi_cpp(IntegerVector k, IntegerVector n, NumericVector a, NumericVector b);
RcppExport SEXP _nilHMM_rtiger_getlogpsi_cpp(SEXP kSEXP, SEXP nSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type k(kSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(rtiger_getlogpsi_cpp(k, n, a, b));
    return rcpp_result_gen;
END_RCPP
}
// rtiger_productpsi_cpp
NumericMatrix rtiger_productpsi_cpp(NumericMatrix logpsi, int r);
RcppExport SEXP _nilHMM_rtiger_productpsi_cpp(SEXP logpsiSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type logpsi(logpsiSEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(rtiger_productpsi_cpp(logpsi, r));
    return rcpp_result_gen;
END_RCPP
}
// rtiger_forward_cpp
NumericMatrix rtiger_forward_cpp(NumericVector logPI, NumericMatrix logPSI, NumericMatrix logA, NumericMatrix logpsi, int r);
RcppExport SEXP _nilHMM_rtiger_forward_cpp(SEXP logPISEXP, SEXP logPSISEXP, SEXP logASEXP, SEXP logpsiSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type logPI(logPISEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type logPSI(logPSISEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type logA(logASEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type logpsi(logpsiSEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(rtiger_forward_cpp(logPI, logPSI, logA, logpsi, r));
    return rcpp_result_gen;
END_RCPP
}
// rtiger_backward_cpp
NumericMatrix rtiger_backward_cpp(NumericMatrix logPSI, NumericMatrix logA, NumericMatrix logpsi, int r);
RcppExport SEXP _nilHMM_rtiger_backward_cpp(SEXP logPSISEXP, SEXP logASEXP, SEXP logpsiSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type logPSI(logPSISEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type logA(logASEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type logpsi(logpsiSEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(rtiger_backward_cpp(logPSI, logA, logpsi, r));
    return rcpp_result_gen;
END_RCPP
}
// rle_segments_cpp
List rle_segments_cpp(IntegerVector path, IntegerVector pos);
RcppExport SEXP _nilHMM_rle_segments_cpp(SEXP pathSEXP, SEXP posSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type path(pathSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type pos(posSEXP);
    rcpp_result_gen = Rcpp::wrap(rle_segments_cpp(path, pos));
    return rcpp_result_gen;
END_RCPP
}
// rle_segments_batch_cpp
List rle_segments_batch_cpp(IntegerMatrix paths, IntegerVector pos);
RcppExport SEXP _nilHMM_rle_segments_batch_cpp(SEXP pathsSEXP, SEXP posSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type paths(pathsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type pos(posSEXP);
    rcpp_result_gen = Rcpp::wrap(rle_segments_batch_cpp(paths, pos));
    return rcpp_result_gen;
END_RCPP
}
// viterbi_log_cpp
IntegerVector viterbi_log_cpp(NumericVector log_init, NumericMatrix log_trans, NumericMatrix log_emit);
RcppExport SEXP _nilHMM_viterbi_log_cpp(SEXP log_initSEXP, SEXP log_transSEXP, SEXP log_emitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type log_init(log_initSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type log_trans(log_transSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type log_emit(log_emitSEXP);
    rcpp_result_gen = Rcpp::wrap(viterbi_log_cpp(log_init, log_trans, log_emit));
    return rcpp_result_gen;
END_RCPP
}
// viterbi_batch_cpp
IntegerMatrix viterbi_batch_cpp(NumericVector log_init, NumericMatrix log_trans, NumericMatrix em_uniq, IntegerMatrix inv);
RcppExport SEXP _nilHMM_viterbi_batch_cpp(SEXP log_initSEXP, SEXP log_transSEXP, SEXP em_uniqSEXP, SEXP invSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type log_init(log_initSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type log_trans(log_transSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type em_uniq(em_uniqSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type inv(invSEXP);
    rcpp_result_gen = Rcpp::wrap(viterbi_batch_cpp(log_init, log_trans, em_uniq, inv));
    return rcpp_result_gen;
END_RCPP
}
// viterbi_batch_par_cpp
IntegerMatrix viterbi_batch_par_cpp(NumericVector log_init, NumericMatrix log_trans, NumericMatrix em_uniq, IntegerMatrix inv);
RcppExport SEXP _nilHMM_viterbi_batch_par_cpp(SEXP log_initSEXP, SEXP log_transSEXP, SEXP em_uniqSEXP, SEXP invSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type log_init(log_initSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type log_trans(log_transSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type em_uniq(em_uniqSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type inv(invSEXP);
    rcpp_result_gen = Rcpp::wrap(viterbi_batch_par_cpp(log_init, log_trans, em_uniq, inv));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_nilHMM_count_emission_loglik_cpp", (DL_FUNC) &_nilHMM_count_emission_loglik_cpp, 4},
    {"_nilHMM_forward_backward_cpp", (DL_FUNC) &_nilHMM_forward_backward_cpp, 3},
    {"_nilHMM_rtiger_getlogpsi_cpp", (DL_FUNC) &_nilHMM_rtiger_getlogpsi_cpp, 4},
    {"_nilHMM_rtiger_productpsi_cpp", (DL_FUNC) &_nilHMM_rtiger_productpsi_cpp, 2},
    {"_nilHMM_rtiger_forward_cpp", (DL_FUNC) &_nilHMM_rtiger_forward_cpp, 5},
    {"_nilHMM_rtiger_backward_cpp", (DL_FUNC) &_nilHMM_rtiger_backward_cpp, 4},
    {"_nilHMM_rle_segments_cpp", (DL_FUNC) &_nilHMM_rle_segments_cpp, 2},
    {"_nilHMM_rle_segments_batch_cpp", (DL_FUNC) &_nilHMM_rle_segments_batch_cpp, 2},
    {"_nilHMM_viterbi_log_cpp", (DL_FUNC) &_nilHMM_viterbi_log_cpp, 3},
    {"_nilHMM_viterbi_batch_cpp", (DL_FUNC) &_nilHMM_viterbi_batch_cpp, 4},
    {"_nilHMM_viterbi_batch_par_cpp", (DL_FUNC) &_nilHMM_viterbi_batch_par_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_nilHMM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
