# Presets layer 2b: breeding-design (generation) axis (S6). Orthogonal to the
# emission axis: a dataset carries BOTH a depth-regime (-> emission) and a
# breeding design (-> generation-derived quantities). e.g. skim = count x BC2S2,
# BRB = count x BC2S3.
#
# Generation determines the single-locus genotype-freq priors (f_1, f_2) and the
# expected fragment-size law (the fitted Gamma). The Gamma is CALIBRATION/NULL
# ONLY -- NEVER an engine prior (S7 circularity trap): baking it into the
# transition would make the caller reproduce it by construction and mask the
# open "callers run longer than the model" signal.

#' Single-locus genotype-frequency priors for a breeding design
#'
#' @param design Design key (e.g. `"BC2S2"`, `"BC2S3"`). Interim hardcoded
#'   values; S6 will move these into the bundled `breeding_designs` dataset
#'   (regenerated by `data-raw/make_breeding_designs.R`).
#' @return `list(g, f_1, f_2)`.
#' @examples
#' design_priors("BC2S2")   # bulked skim
#' design_priors("BC2S3")   # BRB
#' @export
design_priors <- function(design) {
  tab <- list(
    # f_1 = HET freq, f_2 = donor-hom freq (single-locus)
    BC2S2 = list(g = "BC2S2", f_1 = 0.0625, f_2 = 0.0938),  # bulked S3; memory bzea-skim-bulked-bc2s2
    BC2S3 = list(g = "BC2S3", f_1 = 0.0312, f_2 = 0.1094)   # BRB; BRB_run_findings.md
  )
  if (!design %in% names(tab))
    stop("design_priors(): unknown design '", design, "'; have: ",
         paste(names(tab), collapse = ", "))
  tab[[design]]
}

#' Design prior as a length-3 genotype-frequency vector
#'
#' Thin accessor over [design_priors()] that returns the single-locus genotype
#' frequencies as the `c(f_REF, f_HET, f_ALT)` vector consumed directly by
#' [call_gt()] as its `prior`. Keeps the design prior **derived, never typed**.
#'
#' @param design Design key (e.g. `"BC2S2"`, `"BC2S3"`), as for [design_priors()].
#' @return Named numeric length-3 vector `c(REF, HET, ALT)` summing to 1.
#' @examples
#' design_prior("BC2S3")                          # c(REF = .8594, HET = .0312, ALT = .1094)
#' call_gt(0, 1, prior = design_prior("BC2S3"))   # design prior resists the het flip -> 2
#' @seealso [design_priors()], [call_gt()]
#' @export
design_prior <- function(design) {
  d <- design_priors(design)
  c(REF = 1 - d$f_1 - d$f_2, HET = d$f_1, ALT = d$f_2)
}

#' Expected fragment-size distribution (the Null / KS target)
#'
#' Returns the fitted Gamma `(k, lambda)` for a design plus density/CDF
#' closures, for plotting the grey Null and as the KS-vs-sim calibration target.
#' Never feeds the engine transition.
#'
#' @param design Design key.
#' @return `list(k, lambda, density, cdf)`.
#' @examples
#' \dontrun{
#' # Planned (Task 4): the grey Null / KS target for a design.
#' nd <- expected_fragment_dist("BC2S3")
#' }
#' @export
expected_fragment_dist <- function(design) {
  stop("nilHMM::expected_fragment_dist() not yet implemented (Task 4)")
}

#' Fit a design Gamma from simulated segments
#'
#' Extensible entry point used by `data-raw/make_breeding_designs.R` to derive
#' the bundled `(k, lambda)` from simcross output.
#'
#' @param sim_segments data.frame of simulated segment sizes (cM).
#' @return `list(k, lambda)`.
#' @examples
#' \dontrun{
#' # Planned (Task 4): fit the design Gamma from simcross segment sizes.
#' fit_design_gamma(sim_segments)
#' }
#' @export
fit_design_gamma <- function(sim_segments) {
  stop("nilHMM::fit_design_gamma() not yet implemented (Task 4)")
}

#' Convert segment sizes from cM to Mb using a map
#'
#' cM-space Gammas are assembly-robust; anything bp/Mb is tied to B73 v5.
#'
#' @param seg Segments with cM coordinates.
#' @param map A consensus map (see [load_map()]).
#' @return `seg` with Mb coordinates added.
#' @examples
#' \dontrun{
#' # Planned (Task 4): project cM segment coordinates to Mb via a consensus map.
#' cm_to_mb(seg, load_map("v5"))
#' }
#' @export
cm_to_mb <- function(seg, map) {
  stop("nilHMM::cm_to_mb() not yet implemented (Task 4)")
}