# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Log BetaBinomial emission matrix over REF/HET/ALT states
#'
#' @param n Integer vector of total depths (n_ref + n_alt) per marker.
#' @param a Integer vector of alt counts (n_alt) per marker.
#' @param theta Length-K vector of expected alt-fractions per state
#'   (e.g. c(err, 0.5, 1 - err)).
#' @param conc BetaBinomial concentration (alpha + beta); larger -> closer to
#'   Binomial.
#' @return T x K matrix of log emission probabilities.
#' @keywords internal
count_emission_loglik_cpp <- function(n, a, theta, conc) {
    .Call(`_nilHMM_count_emission_loglik_cpp`, n, a, theta, conc)
}

#' Forward-backward state posteriors (log-space; time-homogeneous transitions)
#'
#' @param log_init Length-K log initial-state probabilities.
#' @param log_trans K x K log transition matrix (row = from, col = to).
#' @param log_emit T x K log emission matrix.
#' @return T x K matrix of posterior state probabilities (rows sum to 1).
#' @keywords internal
forward_backward_cpp <- function(log_init, log_trans, log_emit) {
    .Call(`_nilHMM_forward_backward_cpp`, log_init, log_trans, log_emit)
}

#' Interpolate a complete genotype block onto a target cM grid (single chr)
#'
#' Linear flanking-marker interpolation in genetic distance for one chromosome.
#' For a target at cM `t` between called flanking markers L (at `obs_cm[jj]`) and
#' R (at `obs_cm[jj+1]`), the weight is `w = (t - cM_L) / (cM_R - cM_L)` and the
#' continuous dosage is `vL + w*(vR - vL)`. Ends are clamped to the terminal
#' observed value (`stats::approx` rule = 2); tied flanking positions
#' (`denom == 0`) collapse to `w = 0`.
#'
#' @param obs_cm Numeric cM of the observed markers, ascending, length k.
#' @param G Numeric k x n genotype matrix (row = observed marker, col = sample),
#'   COMPLETE (no NA); values are the alt/teosinte-allele dosage in 0 to 2.
#' @param target_cm Numeric cM of the target grid, ascending, length M.
#' @param mode Interpolation mode: 0 = continuous dosage ramp (Tian 2011),
#'   1 = step / nearest flanking value (`w < 0.5 ? vL : vR`, tie `w == 0.5` -> vR;
#'   Chen/TeoNAM), 2 = round(continuous) to 0/1/2.
#' @return Numeric M x n matrix of interpolated genotypes.
#' @keywords internal
interp_geno_cpp <- function(obs_cm, G, target_cm, mode) {
    .Call(`_nilHMM_interp_geno_cpp`, obs_cm, G, target_cm, mode)
}

#' RTIGER emission log-probabilities (getlogpsi)
#'
#' logpsi(i,t) = logpdf(BetaBinomial(n_t, a_i, b_i), k_t). Memoized over distinct
#' (k,n) pairs (as in the fork's getlogpsi cache; bit-identical values).
#' @param k Integer vector of ref-allele counts (length T).
#' @param n Integer vector of totals (length T).
#' @param a,b Per-state BetaBinomial shape vectors (length s).
#' @return s x T matrix of log emission probabilities.
#' @keywords internal
rtiger_getlogpsi_cpp <- function(k, n, a, b) {
    .Call(`_nilHMM_rtiger_getlogpsi_cpp`, k, n, a, b)
}

#' RTIGER windowed emission product (productpsi)
#'
#' PSI(i,t) = sum of psi over the window (t-r+1 .. t) (sliding window of r), as a running
#' cumulative sum. PSI is s x (T+r): the tail columns T+1..T+r-1 carry the
#' trailing partial sums and column T+r is left 0 (exactly as the fork).
#' @param logpsi s x T matrix from rtiger_getlogpsi_cpp.
#' @param r Rigidity.
#' @return s x (T+r) matrix.
#' @keywords internal
rtiger_productpsi_cpp <- function(logpsi, r) {
    .Call(`_nilHMM_rtiger_productpsi_cpp`, logpsi, r)
}

#' RTIGER forward pass (rigidity-aware Baum-Welch forward)
#'
#' Literal port of the fork's `forward`: at each step a state either "stays"
#' (diagonal transition) or was "entered" from another state r positions back.
#' @param logPI length-s log start probabilities.
#' @param logPSI s x (T+r) windowed-emission matrix (rtiger_productpsi_cpp).
#' @param logA s x s log transition matrix.
#' @param logpsi s x T log emission matrix (rtiger_getlogpsi_cpp).
#' @param r Rigidity.
#' @return s x T log forward matrix (cols 1 and >T-r+1 stay -Inf).
#' @keywords internal
rtiger_forward_cpp <- function(logPI, logPSI, logA, logpsi, r) {
    .Call(`_nilHMM_rtiger_forward_cpp`, logPI, logPSI, logA, logpsi, r)
}

#' RTIGER backward pass (rigidity-aware Baum-Welch backward)
#'
#' Literal port of the fork's `backward` (the time-reversed mirror of forward).
#' @inheritParams rtiger_forward_cpp
#' @return s x T log backward matrix.
#' @keywords internal
rtiger_backward_cpp <- function(logPSI, logA, logpsi, r) {
    .Call(`_nilHMM_rtiger_backward_cpp`, logPSI, logA, logpsi, r)
}

#' RTIGER zeta (pairwise posteriors over the rigidity window)
#'
#' Literal port of the fork's `zeta`: build the log values, then normalize by
#' the global max and exponentiate (so exp(-Inf - PO) = 0). Returned as a
#' T x s x s array (column-major), non-log, as in the Julia.
#' @return T x s x s numeric array.
#' @keywords internal
rtiger_zeta_cpp <- function(logalpha, logbeta, logA, logPSI, logpsi, r) {
    .Call(`_nilHMM_rtiger_zeta_cpp`, logalpha, logbeta, logA, logPSI, logpsi, r)
}

#' RTIGER gamma (state posteriors from zeta)
#'
#' Literal port of the fork's `gamma`. Works in linear space (zeta is already
#' exponentiated): the first r columns are the normalized alpha*beta at the
#' window edge; interior columns add the windowed cumulative sum of the
#' off-diagonal zeta to the diagonal term; the tail repeats; columns are then
#' normalized to sum to 1.
#' @param zeta T x s x s array from rtiger_zeta_cpp.
#' @return s x T matrix of state posteriors.
#' @keywords internal
rtiger_gamma_cpp <- function(zeta, logalpha, logbeta, r) {
    .Call(`_nilHMM_rtiger_gamma_cpp`, zeta, logalpha, logbeta, r)
}

#' RTIGER Viterbi (rigidity max-product + rigid backtrace)
#'
#' Literal port of the fork's `viterbi`. Each step is a max over: "stay" in the
#' target state (diagonal), or "enter" it from another state r positions back
#' (using the windowed PSI). The backtrace fills a whole r-block with the
#' current state on a switch, giving the r-rigid path. Tie-break is first state
#' (seed at state 1, replace only on strict >), matching the fork's findmax.
#' @param PI length-s log start probabilities.
#' @param PSI s x (T+r) windowed-emission matrix.
#' @param psi s x T log emission matrix.
#' @param A s x s log transition matrix.
#' @param r Rigidity.
#' @return length-T integer state path (1-based states).
#' @keywords internal
rtiger_viterbi_cpp <- function(PI, PSI, psi, A, r) {
    .Call(`_nilHMM_rtiger_viterbi_cpp`, PI, PSI, psi, A, r)
}

#' RTIGER one-EM-iteration sufficient statistics (E-step + fold, all in C++)
#'
#' Runs the per-chain E-step (getlogpsi..gamma) and accumulates the pooled
#' sufficient statistics, replacing the slow R-level fold (apply()/tapply()).
#' Mirrors the fork's EM accumulation: transition band-sum of zeta, start =
#' Sum of gamma column 1, and per-state emission weights grouped by distinct (k,n).
#' @param ks_list,ns_list Lists of per-chain integer (k, n) vectors.
#' @param logPI,logA log start / log transition.
#' @param alpha,beta current BetaBinomial shape vectors.
#' @param r,nstates Rigidity and number of states.
#' @return list(sumZeta, startAcc, nOb, kvals, nvals, wmat, sumk, sumn).
#' @keywords internal
rtiger_em_suffstats_cpp <- function(ks_list, ns_list, logPI, logA, alpha, beta, r, nstates) {
    .Call(`_nilHMM_rtiger_em_suffstats_cpp`, ks_list, ns_list, logPI, logA, alpha, beta, r, nstates)
}

#' RTIGER full EM fit (E-step + M-step + convergence loop, all in C++)
#'
#' The entire fit (port of the fork's `fit`/`EM`): per-chain rigidity E-step,
#' pooled M-steps (transition, start, emission via C++ Brent), iterated until
#' max(|Δα|,|Δβ|) <= eps or max.iter. Deterministic init (generate_params forms,
#' randomize off). Returns the fitted parameters and iteration count.
#' @param ks_list,ns_list Lists of per-chain integer (k, n) vectors.
#' @param r,nstates Rigidity and number of states.
#' @param eps,max_iter Convergence tolerance and iteration cap.
#' @return list(A, pi, alpha, beta, iterations).
#' @keywords internal
rtiger_fit_cpp <- function(ks_list, ns_list, r, nstates, eps, max_iter, threads, init_alpha, init_beta) {
    .Call(`_nilHMM_rtiger_fit_cpp`, ks_list, ns_list, r, nstates, eps, max_iter, threads, init_alpha, init_beta)
}

#' Run-length-encode a state path into (start_bp, end_bp, state) segments
#'
#' @param path Integer state path (0/1/2), length T.
#' @param pos Integer marker positions, length T (same order as path).
#' @return List of equal-length integer vectors: start_bp, end_bp, state.
#' @keywords internal
rle_segments_cpp <- function(path, pos) {
    .Call(`_nilHMM_rle_segments_cpp`, path, pos)
}

#' Run-length-encode a batch of state paths (one per column) into segments
#'
#' @param paths T x S integer matrix of state paths (column = sample).
#' @param pos Integer marker positions, length T (shared across samples).
#' @return List of equal-length vectors: sample (1-based column), start_bp,
#'   end_bp, state.
#' @keywords internal
rle_segments_batch_cpp <- function(paths, pos) {
    .Call(`_nilHMM_rle_segments_batch_cpp`, paths, pos)
}

#' Generic log-space Viterbi decode (time-homogeneous transitions)
#'
#' @param log_init Length-K vector of log initial-state probabilities.
#' @param log_trans K x K matrix of log transition probabilities
#'   (row = from-state, column = to-state).
#' @param log_emit T x K matrix of log emission probabilities per marker/state.
#' @return Integer length-T most-likely state path, 0-indexed.
#' @keywords internal
viterbi_log_cpp <- function(log_init, log_trans, log_emit) {
    .Call(`_nilHMM_viterbi_log_cpp`, log_init, log_trans, log_emit)
}

#' Batched log-space Viterbi (shared transition, memoized emission)
#'
#' @param log_init Length-K log initial-state probabilities.
#' @param log_trans K x K log transition matrix (row = from, col = to).
#' @param em_uniq U x K log emission table, one row per distinct observation.
#' @param inv T x S integer matrix; inv(t,s) is the 0-based row of `em_uniq`
#'   giving the emission for sample s at marker t.
#' @return T x S integer matrix of most-likely state paths (0-based states).
#' @keywords internal
viterbi_batch_cpp <- function(log_init, log_trans, em_uniq, inv) {
    .Call(`_nilHMM_viterbi_batch_cpp`, log_init, log_trans, em_uniq, inv)
}

#' Threaded batched log-space Viterbi (RcppParallel)
#'
#' Identical result to [viterbi_batch_cpp]; splits the sample axis across cores.
#' @inheritParams viterbi_batch_cpp
#' @return T x S integer matrix of most-likely state paths (0-based).
#' @keywords internal
viterbi_batch_par_cpp <- function(log_init, log_trans, em_uniq, inv) {
    .Call(`_nilHMM_viterbi_batch_par_cpp`, log_init, log_trans, em_uniq, inv)
}

