# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Generic log-space Viterbi decode (time-homogeneous transitions)
#'
#' @param log_init Length-K vector of log initial-state probabilities.
#' @param log_trans K x K matrix of log transition probabilities
#'   (row = from-state, column = to-state).
#' @param log_emit T x K matrix of log emission probabilities per marker/state.
#' @return Integer length-T most-likely state path, 0-indexed.
#' @keywords internal
viterbi_log_cpp <- function(log_init, log_trans, log_emit) {
    .Call(`_nilHMM_viterbi_log_cpp`, log_init, log_trans, log_emit)
}

