# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Log BetaBinomial emission matrix over REF/HET/ALT states
#'
#' @param n Integer vector of total depths (n_ref + n_alt) per marker.
#' @param a Integer vector of alt counts (n_alt) per marker.
#' @param theta Length-K vector of expected alt-fractions per state
#'   (e.g. c(err, 0.5, 1 - err)).
#' @param conc BetaBinomial concentration (alpha + beta); larger -> closer to
#'   Binomial.
#' @return T x K matrix of log emission probabilities.
#' @keywords internal
count_emission_loglik_cpp <- function(n, a, theta, conc) {
    .Call(`_nilHMM_count_emission_loglik_cpp`, n, a, theta, conc)
}

#' Forward-backward state posteriors (log-space; time-homogeneous transitions)
#'
#' @param log_init Length-K log initial-state probabilities.
#' @param log_trans K x K log transition matrix (row = from, col = to).
#' @param log_emit T x K log emission matrix.
#' @return T x K matrix of posterior state probabilities (rows sum to 1).
#' @keywords internal
forward_backward_cpp <- function(log_init, log_trans, log_emit) {
    .Call(`_nilHMM_forward_backward_cpp`, log_init, log_trans, log_emit)
}

#' Run-length-encode a state path into (start_bp, end_bp, state) segments
#'
#' @param path Integer state path (0/1/2), length T.
#' @param pos Integer marker positions, length T (same order as path).
#' @return List of equal-length integer vectors: start_bp, end_bp, state.
#' @keywords internal
rle_segments_cpp <- function(path, pos) {
    .Call(`_nilHMM_rle_segments_cpp`, path, pos)
}

#' Run-length-encode a batch of state paths (one per column) into segments
#'
#' @param paths T x S integer matrix of state paths (column = sample).
#' @param pos Integer marker positions, length T (shared across samples).
#' @return List of equal-length vectors: sample (1-based column), start_bp,
#'   end_bp, state.
#' @keywords internal
rle_segments_batch_cpp <- function(paths, pos) {
    .Call(`_nilHMM_rle_segments_batch_cpp`, paths, pos)
}

#' Generic log-space Viterbi decode (time-homogeneous transitions)
#'
#' @param log_init Length-K vector of log initial-state probabilities.
#' @param log_trans K x K matrix of log transition probabilities
#'   (row = from-state, column = to-state).
#' @param log_emit T x K matrix of log emission probabilities per marker/state.
#' @return Integer length-T most-likely state path, 0-indexed.
#' @keywords internal
viterbi_log_cpp <- function(log_init, log_trans, log_emit) {
    .Call(`_nilHMM_viterbi_log_cpp`, log_init, log_trans, log_emit)
}

#' Batched log-space Viterbi (shared transition, memoized emission)
#'
#' @param log_init Length-K log initial-state probabilities.
#' @param log_trans K x K log transition matrix (row = from, col = to).
#' @param em_uniq U x K log emission table, one row per distinct observation.
#' @param inv T x S integer matrix; inv(t,s) is the 0-based row of `em_uniq`
#'   giving the emission for sample s at marker t.
#' @return T x S integer matrix of most-likely state paths (0-based states).
#' @keywords internal
viterbi_batch_cpp <- function(log_init, log_trans, em_uniq, inv) {
    .Call(`_nilHMM_viterbi_batch_cpp`, log_init, log_trans, em_uniq, inv)
}

